export const EVENT_TYPES = {
  BALL: 'BALL',
  BOUNDARY: 'BOUNDARY',
  WICKET: 'WICKET',
  MATCH_STATUS: 'MATCH_STATUS',
  UNKNOWN: 'UNKNOWN',
};

export const MAX_BALLS = 120;
export const MAX_WICKETS = 10;